---
- hosts: all
  sudo: yes
  tasks:

    - name: epel-release
      yum: name=epel-release state=installed

    - name: Add repository 'remi-repo'
      command: rpm -ih http://rpms.famillecollet.com/enterprise/remi-release-7.rpm creates=/etc/yum.repos.d/remi.repo

    - name: install php70
      yum: name={{ item }} enablerepo=epel,remi,remi-php70 state=installed
      with_items:
        - php70
