# これはまだ全然仮実装です
- name: add repo
  command: rpm -ih http://dev.mysql.com/get/mysql57-community-release-el7-7.noarch.rpm creates=/etc/yum.repos.d/mysql-community.repo

- name: install mysql-community-server
  yum: name=mysql-community-server state=installed

- name: start server
  service: name=mysqld state=started enabled=yes

#
# sudo grep 'temporary password' /var/log/mysqld.log
# mysql> ALTER USER 'root'@'localhost' IDENTIFIED BY 'MyNewPass4!';
