# install MySQL 5.7 on CentOS7.1
# これはまだ全然仮実装です
- name: add repo
  command: rpm -ih http://dev.mysql.com/get/mysql57-community-release-el7-7.noarch.rpm creates=/etc/yum.repos.d/mysql-community.repo

- name: install mysql-community-server
  yum: name=mysql-community-server state=installed

- name: install MySQL-python for ansible mysql_user module
  yum: name=MySQL-python state=installed

- name: put my.cnf file
  copy: src=my.cnf dest=/etc/my.cnf owner=root mode=0644

- name: start server
  service: name=mysqld state=started enabled=yes

- name: save-mysql-tmp-password.sh
  script: save-mysql-tmp-password.sh creates=/root/.tmp.my.cnf

- name: set new password
  script: change-root-password.sh creates=/root/.my.cnf

- name: create databases
  script: create-databases.sh creates=/root/db_created

- name: create users and grants
  script: create-grant-users.sh creates=/root/db_user_created

